//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GtdAppModel", "ContextTodo", "Context", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GtdApp.Entities.Context), "Todo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GtdApp.Entities.Todo), true)]

#endregion

namespace GtdApp.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GtdAppDataContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GtdAppDataContext object using the connection string found in the 'GtdAppDataContext' section of the application configuration file.
        /// </summary>
        public GtdAppDataContext() : base("name=GtdAppDataContext", "GtdAppDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GtdAppDataContext object.
        /// </summary>
        public GtdAppDataContext(string connectionString) : base(connectionString, "GtdAppDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GtdAppDataContext object.
        /// </summary>
        public GtdAppDataContext(EntityConnection connection) : base(connection, "GtdAppDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Context> Contexts
        {
            get
            {
                if ((_Contexts == null))
                {
                    _Contexts = base.CreateObjectSet<Context>("Contexts");
                }
                return _Contexts;
            }
        }
        private ObjectSet<Context> _Contexts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Todo> Todos
        {
            get
            {
                if ((_Todos == null))
                {
                    _Todos = base.CreateObjectSet<Todo>("Todos");
                }
                return _Todos;
            }
        }
        private ObjectSet<Todo> _Todos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contexts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContexts(Context context)
        {
            base.AddObject("Contexts", context);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Todos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTodos(Todo todo)
        {
            base.AddObject("Todos", todo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GtdAppModel", Name="Context")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Context : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Context object.
        /// </summary>
        /// <param name="contextId">Initial value of the ContextId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Context CreateContext(global::System.Guid contextId, global::System.String name)
        {
            Context context = new Context();
            context.ContextId = contextId;
            context.Name = name;
            return context;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ContextId
        {
            get
            {
                return _ContextId;
            }
            set
            {
                if (_ContextId != value)
                {
                    OnContextIdChanging(value);
                    ReportPropertyChanging("ContextId");
                    _ContextId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ContextId");
                    OnContextIdChanged();
                }
            }
        }
        private global::System.Guid _ContextId;
        partial void OnContextIdChanging(global::System.Guid value);
        partial void OnContextIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GtdAppModel", "ContextTodo", "Todo")]
        public EntityCollection<Todo> Todos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Todo>("GtdAppModel.ContextTodo", "Todo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Todo>("GtdAppModel.ContextTodo", "Todo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GtdAppModel", Name="Todo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Todo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Todo object.
        /// </summary>
        /// <param name="todoId">Initial value of the TodoId property.</param>
        /// <param name="contextId">Initial value of the ContextId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="isDone">Initial value of the IsDone property.</param>
        public static Todo CreateTodo(global::System.Guid todoId, global::System.Guid contextId, global::System.String name, global::System.Boolean isDone)
        {
            Todo todo = new Todo();
            todo.TodoId = todoId;
            todo.ContextId = contextId;
            todo.Name = name;
            todo.IsDone = isDone;
            return todo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TodoId
        {
            get
            {
                return _TodoId;
            }
            set
            {
                if (_TodoId != value)
                {
                    OnTodoIdChanging(value);
                    ReportPropertyChanging("TodoId");
                    _TodoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TodoId");
                    OnTodoIdChanged();
                }
            }
        }
        private global::System.Guid _TodoId;
        partial void OnTodoIdChanging(global::System.Guid value);
        partial void OnTodoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ContextId
        {
            get
            {
                return _ContextId;
            }
            set
            {
                OnContextIdChanging(value);
                ReportPropertyChanging("ContextId");
                _ContextId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContextId");
                OnContextIdChanged();
            }
        }
        private global::System.Guid _ContextId;
        partial void OnContextIdChanging(global::System.Guid value);
        partial void OnContextIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDone
        {
            get
            {
                return _IsDone;
            }
            set
            {
                OnIsDoneChanging(value);
                ReportPropertyChanging("IsDone");
                _IsDone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDone");
                OnIsDoneChanged();
            }
        }
        private global::System.Boolean _IsDone;
        partial void OnIsDoneChanging(global::System.Boolean value);
        partial void OnIsDoneChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GtdAppModel", "ContextTodo", "Context")]
        public Context Context
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Context>("GtdAppModel.ContextTodo", "Context").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Context>("GtdAppModel.ContextTodo", "Context").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Context> ContextReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Context>("GtdAppModel.ContextTodo", "Context");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Context>("GtdAppModel.ContextTodo", "Context", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
